config/routes.rb
Polski::Application.routes.draw do
  resources :fortunes

  root :to => 'fortunes#index'

end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  attr_accessible :quotation, :source

  validates :quotation, :presence => true, :length => { :maximum => 100 }
  validates :source, :length => { :minimum => 2, :maximum => 40 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: t('flash.fortunes.create.notice') }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: t('flash.fortunes.update.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/layout_helper.rb
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
#
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  def show_title?
    @show_title
  end
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/common/_flashes.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
  <a class="close" data-dismiss="alert">×</a>
  <%= msg %>
</div>
<% end %>

app/views/common/_footer.html.erb
<p><small>&copy; Powered by Rails 3.2 &amp; Bootstrap 2.0, from Twitter</small>

app/views/common/_menu.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<a class="brand" href="#">I18N</a>
<div class="nav-collapse">
  <ul class="nav">
    <li><%= link_to "Home", '#' %>
    <li><%= link_to "About", '#' %>
    <li><%= link_to "Contact", '#' %>
  </ul>
</div>

app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quotation, :input_html => { :rows => 6 } %>
    <%= f.input :source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<% title t ".title" %>

<%= render partial: 'form'%>

app/views/fortunes/index.html.erb
<% title t ".title" %>

<% @fortunes.each do |fortune| %>
<article class="index">
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.quotation" %></span>
    <span class="value"><%= fortune.quotation %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.source" %></span>
    <span class="value"><%= fortune.source %></span>
  </div>
<div class="form-actions">
  <%= link_to t('show'), fortune, class: 'btn btn-mini'%>
  <%= link_to t('edit'), edit_fortune_path(fortune), class: 'btn btn-mini'%>
  <%= link_to t('destroy'), fortune, confirm: t('confirm'), method: :delete, class: 'btn btn-mini btn-danger'%>
</div>
</article>
<% end %>

<div class="form-actions">
  <%= link_to t('.new'), new_fortune_path, class: 'btn btn-primary'%>
</div>

app/views/fortunes/new.html.erb
<% title t ".title" %>

<%= render partial: 'form'%>

app/views/fortunes/show.html.erb
<% title t ".title" %>

<article class="show">
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.quotation" %></span>
    <span class="value"><%= @fortune.quotation %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.source" %></span>
    <span class="value"><%= @fortune.source %></span>
  </div>
<div class="form-actions">
  <%= link_to t('back'), fortunes_path, class: 'btn'%>
  <%= link_to t('edit'), edit_fortune_path(@fortune), class: 'btn' %>
  <%= link_to t('destroy'), @fortune, confirm: t('confirm'), method: :delete, class: 'btn btn-danger'%>
</div>
</article>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "I18N" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= render :partial => 'common/menu' %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= render :partial => 'common/flashes' %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
      <footer>
        <%= render :partial => 'common/footer' %>
      </footer>
    </div>

  </body>
</html>